# Generated by Django 4.2.5 on 2023-12-21 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['-created_on']},
        ),
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=6)),
                ('unit', models.CharField(choices=[('tsp', 'tsp'), ('Tbsp', 'Tbsp'), ('fl oz', 'fl oz'), ('cp', 'cp'), ('pt', 'pt'), ('qt', 'qt'), ('gal', 'gal'), ('ml', 'ml'), ('l', 'l'), ('oz', 'oz'), ('lb', 'lb'), ('mg', 'mg'), ('g', 'g'), ('kg', 'kg')], max_length=5)),
                ('system', models.CharField(choices=[('us', 'us'), ('metric', 'metric')], editable=False, max_length=6)),
                ('attribute', models.CharField(choices=[('volume', 'volume'), ('weight', 'weight')], editable=False, max_length=6)),
                ('conversion_multiple', models.DecimalField(decimal_places=3, max_digits=13)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ingredient')),
            ],
            options={
                'verbose_name_plural': 'Quantities',
                'ordering': ['-created_on'],
            },
        ),
    ]
