# Generated by Django 4.2.5 on 2023-12-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('ingredients', models.ManyToManyField(blank=True, to='core.quantity')),
                ('recipes', models.ManyToManyField(blank=True, to='core.recipe')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
