# Generated by Django 4.2.5 on 2023-12-28 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_ingredient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantities', to='core.ingredient'),
        ),
    ]
