# Generated by Django 4.2.5 on 2023-12-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_list_ingredients_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='recipes',
            field=models.ManyToManyField(blank=True, related_name='lists', to='core.recipe'),
        ),
    ]
